-- Enable RLS for Supabase-exposed tables. The application uses Prisma with the
-- database connection string; client-side Supabase API access remains closed by
-- default until explicit policies are added.
ALTER TABLE "Organization" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrganizationSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Profile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Client" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ClientContact" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Opportunity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Case" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CaseStatusHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CaseAssignee" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CaseMilestone" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CaseChecklist" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Document" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Shipment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Container" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Flight" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TransportMission" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CustomsDeclaration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CustomsEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExpenseRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExpenseApproval" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CashTransaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Invoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InvoiceItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Payment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Incident" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Comment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExchangeRate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ServiceCatalog" ENABLE ROW LEVEL SECURITY;

-- Foreign-key and tenant indexes for operational performance.
CREATE INDEX IF NOT EXISTS "Profile_organizationId_idx" ON "Profile"("organizationId");
CREATE INDEX IF NOT EXISTS "Client_organizationId_idx" ON "Client"("organizationId");
CREATE INDEX IF NOT EXISTS "ClientContact_clientId_idx" ON "ClientContact"("clientId");
CREATE INDEX IF NOT EXISTS "Opportunity_organizationId_idx" ON "Opportunity"("organizationId");
CREATE INDEX IF NOT EXISTS "Opportunity_clientId_idx" ON "Opportunity"("clientId");
CREATE INDEX IF NOT EXISTS "Case_organizationId_idx" ON "Case"("organizationId");
CREATE INDEX IF NOT EXISTS "Case_clientId_idx" ON "Case"("clientId");
CREATE INDEX IF NOT EXISTS "Case_commercialId_idx" ON "Case"("commercialId");
CREATE INDEX IF NOT EXISTS "Case_serviceChefId_idx" ON "Case"("serviceChefId");
CREATE INDEX IF NOT EXISTS "Case_status_priority_idx" ON "Case"("status", "priority");
CREATE INDEX IF NOT EXISTS "CaseStatusHistory_caseId_idx" ON "CaseStatusHistory"("caseId");
CREATE INDEX IF NOT EXISTS "CaseAssignee_profileId_idx" ON "CaseAssignee"("profileId");
CREATE INDEX IF NOT EXISTS "CaseMilestone_caseId_idx" ON "CaseMilestone"("caseId");
CREATE INDEX IF NOT EXISTS "CaseChecklist_caseId_idx" ON "CaseChecklist"("caseId");
CREATE INDEX IF NOT EXISTS "Document_caseId_idx" ON "Document"("caseId");
CREATE INDEX IF NOT EXISTS "Document_organizationId_idx" ON "Document"("organizationId");
CREATE INDEX IF NOT EXISTS "Shipment_caseId_idx" ON "Shipment"("caseId");
CREATE INDEX IF NOT EXISTS "Container_shipmentId_idx" ON "Container"("shipmentId");
CREATE INDEX IF NOT EXISTS "Flight_caseId_idx" ON "Flight"("caseId");
CREATE INDEX IF NOT EXISTS "TransportMission_caseId_idx" ON "TransportMission"("caseId");
CREATE INDEX IF NOT EXISTS "TransportMission_organizationId_idx" ON "TransportMission"("organizationId");
CREATE INDEX IF NOT EXISTS "CustomsDeclaration_caseId_idx" ON "CustomsDeclaration"("caseId");
CREATE INDEX IF NOT EXISTS "CustomsEvent_declarationId_idx" ON "CustomsEvent"("declarationId");
CREATE INDEX IF NOT EXISTS "ExpenseRequest_organizationId_idx" ON "ExpenseRequest"("organizationId");
CREATE INDEX IF NOT EXISTS "ExpenseRequest_caseId_idx" ON "ExpenseRequest"("caseId");
CREATE INDEX IF NOT EXISTS "ExpenseRequest_requesterId_idx" ON "ExpenseRequest"("requesterId");
CREATE INDEX IF NOT EXISTS "ExpenseRequest_status_idx" ON "ExpenseRequest"("status");
CREATE INDEX IF NOT EXISTS "ExpenseApproval_expenseId_idx" ON "ExpenseApproval"("expenseId");
CREATE INDEX IF NOT EXISTS "ExpenseApproval_approverId_idx" ON "ExpenseApproval"("approverId");
CREATE INDEX IF NOT EXISTS "CashTransaction_organizationId_idx" ON "CashTransaction"("organizationId");
CREATE INDEX IF NOT EXISTS "CashTransaction_performedById_idx" ON "CashTransaction"("performedById");
CREATE INDEX IF NOT EXISTS "Invoice_organizationId_idx" ON "Invoice"("organizationId");
CREATE INDEX IF NOT EXISTS "Invoice_caseId_idx" ON "Invoice"("caseId");
CREATE INDEX IF NOT EXISTS "Invoice_clientId_idx" ON "Invoice"("clientId");
CREATE INDEX IF NOT EXISTS "Invoice_status_dueDate_idx" ON "Invoice"("status", "dueDate");
CREATE INDEX IF NOT EXISTS "InvoiceItem_invoiceId_idx" ON "InvoiceItem"("invoiceId");
CREATE INDEX IF NOT EXISTS "Payment_invoiceId_idx" ON "Payment"("invoiceId");
CREATE INDEX IF NOT EXISTS "Payment_clientId_idx" ON "Payment"("clientId");
CREATE INDEX IF NOT EXISTS "Incident_organizationId_idx" ON "Incident"("organizationId");
CREATE INDEX IF NOT EXISTS "Incident_caseId_idx" ON "Incident"("caseId");
CREATE INDEX IF NOT EXISTS "Incident_status_severity_idx" ON "Incident"("status", "severity");
CREATE INDEX IF NOT EXISTS "Notification_organizationId_profileId_idx" ON "Notification"("organizationId", "profileId");
CREATE INDEX IF NOT EXISTS "Comment_caseId_idx" ON "Comment"("caseId");
CREATE INDEX IF NOT EXISTS "Comment_profileId_idx" ON "Comment"("profileId");
CREATE INDEX IF NOT EXISTS "AuditLog_organizationId_idx" ON "AuditLog"("organizationId");
CREATE INDEX IF NOT EXISTS "ServiceCatalog_organizationId_idx" ON "ServiceCatalog"("organizationId");
