ALTER TABLE "CustomsDeclaration"
  ADD COLUMN IF NOT EXISTS "hsCode" TEXT,
  ADD COLUMN IF NOT EXISTS "hsDescription" TEXT,
  ADD COLUMN IF NOT EXISTS "tariffRate" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "countryOfOrigin" TEXT,
  ADD COLUMN IF NOT EXISTS "countryOfDestination" TEXT,
  ADD COLUMN IF NOT EXISTS "customsValue" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "customsValueCurrency" TEXT NOT NULL DEFAULT 'GNF',
  ADD COLUMN IF NOT EXISTS "dutyAmount" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "vatAmount" DOUBLE PRECISION;

CREATE INDEX IF NOT EXISTS "CustomsDeclaration_hsCode_idx" ON "CustomsDeclaration"("hsCode");
