'use client'

import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Check, Crown, ExternalLink, HardDrive, Loader2, Sparkles, Users, FolderOpen } from 'lucide-react'
import { toast } from 'sonner'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Progress } from '@/components/ui/progress'
import { Switch } from '@/components/ui/switch'

type Plan = { id: string; code: string; name: string; description: string | null; monthlyPrice: number; annualPrice: number; currency: string; maxCasesPerMonth: number | null; maxUsers: number | null; maxStorageBytes: string | null; features: string[] }
type Payload = { subscription: { id: string; status: string; billingCycle: string; currentPeriodEnd: string | null; cancelAtPeriodEnd: boolean; providerCustomerId: string | null; plan: Plan }; plans: Plan[]; usage: { cases: number; users: number; storageBytes: number; periodEnd: string }; payments: Array<{ id: string; amount: number; currency: string; status: string; paidAt: string | null; createdAt: string; receiptUrl: string | null }>; providers: { stripe: boolean; orangeMoney: boolean } }

const nf = new Intl.NumberFormat('fr-FR')
const money = (value: number, currency = 'GNF') => value === 0 ? 'Sur devis' : `${nf.format(value)} ${currency}`
const bytes = (value: number) => value >= 1024 ** 3 ? `${(value / 1024 ** 3).toFixed(1)} Go` : `${(value / 1024 ** 2).toFixed(0)} Mo`

function Usage({ icon: Icon, label, used, limit, display }: { icon: typeof Users; label: string; used: number; limit: number | null; display?: (value: number) => string }) {
  const percent = limit ? Math.min(100, used / limit * 100) : 0
  return <div className="space-y-2 rounded-xl border bg-background/70 p-4"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-sm font-medium"><Icon className="size-4 text-primary" />{label}</span><span className="text-sm tabular-nums text-muted-foreground">{display ? display(used) : nf.format(used)} / {limit === null ? 'Illimité' : display ? display(limit) : nf.format(limit)}</span></div><Progress value={limit === null ? 0 : percent} className="h-2" /></div>
}

export default function SubscriptionView() {
  const [annual, setAnnual] = useState(true)
  const [busy, setBusy] = useState<string | null>(null)
  const { data, error, isLoading } = useQuery<Payload>({ queryKey: ['saas-subscription'], queryFn: async () => { const response = await fetch('/api/saas/subscription'); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Chargement impossible'); return body } })

  async function checkout(plan: Plan) {
    if (plan.code === 'enterprise') { window.location.assign('mailto:contact@igsgf.com?subject=Offre Enterprise IGS Nexus'); return }
    setBusy(plan.code)
    try { const response = await fetch('/api/saas/checkout', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ plan: plan.code, billingCycle: annual ? 'annual' : 'monthly' }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); if (body.url) window.location.assign(body.url); else if (body.contactUrl) window.location.assign(body.contactUrl) } catch (e) { toast.error(e instanceof Error ? e.message : 'Paiement indisponible') } finally { setBusy(null) }
  }
  async function openPortal() { setBusy('portal'); try { const response = await fetch('/api/saas/portal', { method: 'POST' }); const body = await response.json(); if (!response.ok) throw new Error(body.error); window.location.assign(body.url) } catch (e) { toast.error(e instanceof Error ? e.message : 'Portail indisponible') } finally { setBusy(null) } }

  if (isLoading) return <div className="flex min-h-[420px] items-center justify-center"><Loader2 className="size-8 animate-spin text-primary" /></div>
  if (error || !data) return <Card><CardContent className="p-8 text-center text-destructive">{error instanceof Error ? error.message : 'Abonnement indisponible'}</CardContent></Card>
  const current = data.subscription
  return <div className="space-y-8">
    <section className="relative overflow-hidden rounded-2xl border bg-[linear-gradient(120deg,#102c28_0%,#17463d_65%,#ef6c22_150%)] p-6 text-white shadow-xl md:p-8"><div className="absolute -right-12 -top-20 size-64 rounded-full border border-white/10 bg-white/5" /><div className="relative flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><Badge className="mb-4 border-white/20 bg-white/10 text-white"><Sparkles className="mr-1 size-3" /> Abonnement plateforme</Badge><h1 className="text-3xl font-bold tracking-tight md:text-4xl">Votre capacité opérationnelle, maîtrisée.</h1><p className="mt-2 max-w-2xl text-sm text-white/70">Gérez le plan IGS Nexus, les quotas et les règlements de votre organisation indépendamment de vos factures clients.</p></div><div className="min-w-64 rounded-xl border border-white/15 bg-black/15 p-4 backdrop-blur"><p className="text-xs uppercase tracking-widest text-white/60">Plan actuel</p><div className="mt-1 flex items-center justify-between"><span className="text-2xl font-bold">{current.plan.name}</span><Badge className="bg-emerald-400/15 text-emerald-100">{current.status}</Badge></div><p className="mt-2 text-xs text-white/60">Échéance : {current.currentPeriodEnd ? new Date(current.currentPeriodEnd).toLocaleDateString('fr-FR') : 'sur mesure'}</p>{current.providerCustomerId ? <Button size="sm" variant="secondary" className="mt-4 w-full" onClick={openPortal} disabled={busy === 'portal'}>{busy === 'portal' ? <Loader2 className="mr-2 size-4 animate-spin" /> : <ExternalLink className="mr-2 size-4" />}Gérer le paiement</Button> : null}</div></div></section>
    <section><div className="mb-4"><h2 className="text-xl font-semibold">Utilisation du plan</h2><p className="text-sm text-muted-foreground">Dossiers remis à zéro chaque mois. Le stockage et les utilisateurs sont calculés en temps réel.</p></div><div className="grid gap-4 md:grid-cols-3"><Usage icon={FolderOpen} label="Dossiers ce mois" used={data.usage.cases} limit={current.plan.maxCasesPerMonth} /><Usage icon={Users} label="Utilisateurs actifs" used={data.usage.users} limit={current.plan.maxUsers} /><Usage icon={HardDrive} label="Stockage documentaire" used={data.usage.storageBytes} limit={current.plan.maxStorageBytes ? Number(current.plan.maxStorageBytes) : null} display={bytes} /></div></section>
    <section><div className="mb-5 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-xl font-semibold">Plans IGS Nexus</h2><p className="text-sm text-muted-foreground">Économisez deux mois avec la facturation annuelle.</p></div><label className="flex items-center gap-3 rounded-full border px-4 py-2 text-sm"><span>Mensuel</span><Switch checked={annual} onCheckedChange={setAnnual} /><span>Annuel</span></label></div><div className="grid gap-5 lg:grid-cols-3">{data.plans.map((plan) => { const selected = plan.code === current.plan.code; const features = Array.isArray(plan.features) ? plan.features : []; return <Card key={plan.id} className={selected ? 'relative border-primary shadow-[0_18px_50px_rgb(239_108_34/0.14)]' : 'relative'}>{selected ? <Badge className="absolute right-4 top-4">Actuel</Badge> : null}<CardHeader><div className="mb-2 flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary">{plan.code === 'enterprise' ? <Crown className="size-5" /> : <Sparkles className="size-5" />}</div><CardTitle>{plan.name}</CardTitle><p className="min-h-10 text-sm text-muted-foreground">{plan.description}</p><p className="pt-3 text-2xl font-bold">{money(annual ? plan.annualPrice : plan.monthlyPrice, plan.currency)}</p><p className="text-xs text-muted-foreground">{plan.code === 'enterprise' ? 'Contrat et SLA personnalisés' : annual ? 'par an' : 'par mois'}</p></CardHeader><CardContent className="space-y-5"><ul className="space-y-2">{features.map((feature) => <li key={feature} className="flex gap-2 text-sm"><Check className="mt-0.5 size-4 shrink-0 text-emerald-600" />{feature}</li>)}</ul><Button className="w-full" variant={selected ? 'outline' : 'default'} disabled={selected || busy === plan.code} onClick={() => checkout(plan)}>{busy === plan.code ? <Loader2 className="mr-2 size-4 animate-spin" /> : null}{selected ? 'Plan actuel' : plan.code === 'enterprise' ? 'Contacter les ventes' : 'Choisir ce plan'}</Button></CardContent></Card> })}</div>{!data.providers.stripe ? <p className="mt-4 rounded-lg border border-amber-300/50 bg-amber-50 p-3 text-sm text-amber-900">Le paiement par carte sera disponible après configuration du compte marchand Stripe. Orange Money est prévu comme canal local dès validation de vos identifiants marchand Orange.</p> : null}</section>
    <section><h2 className="mb-4 text-xl font-semibold">Historique des paiements plateforme</h2><Card><CardContent className="p-0">{data.payments.length === 0 ? <p className="p-8 text-center text-sm text-muted-foreground">Aucun règlement d’abonnement enregistré.</p> : <div className="divide-y">{data.payments.map((payment) => <div key={payment.id} className="flex flex-col justify-between gap-2 p-4 sm:flex-row sm:items-center"><div><p className="font-medium">{money(payment.amount, payment.currency)}</p><p className="text-xs text-muted-foreground">{new Date(payment.paidAt || payment.createdAt).toLocaleDateString('fr-FR')}</p></div><div className="flex items-center gap-3"><Badge variant="outline">{payment.status}</Badge>{payment.receiptUrl ? <a href={payment.receiptUrl} target="_blank" rel="noreferrer" className="text-sm font-medium text-primary">Reçu</a> : null}</div></div>)}</div>}</CardContent></Card></section>
  </div>
}
