ALTER TABLE "Invoice"
  ADD COLUMN IF NOT EXISTS "supplyDate" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "discountAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "vatRegime" TEXT NOT NULL DEFAULT 'standard',
  ADD COLUMN IF NOT EXISTS "vatLegalReference" TEXT,
  ADD COLUMN IF NOT EXISTS "vatWithholdingRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "vatWithholdingAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "withholdingTaxRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "withholdingTaxAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "amountPayable" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "paymentTerms" TEXT,
  ADD COLUMN IF NOT EXISTS "purchaseOrderRef" TEXT;

UPDATE "Invoice"
SET "amountPayable" = "netAmount"
WHERE "amountPayable" = 0 AND "netAmount" > 0;

ALTER TABLE "InvoiceItem"
  ADD COLUMN IF NOT EXISTS "unit" TEXT NOT NULL DEFAULT 'unité',
  ADD COLUMN IF NOT EXISTS "discountRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 18,
  ADD COLUMN IF NOT EXISTS "taxAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS "Invoice_organizationId_invoiceNumber_key"
  ON "Invoice"("organizationId", "invoiceNumber");
