'use client'

import { Fragment, useMemo, useState, type FormEvent } from 'react'
import { keepPreviousData, useQuery, useQueryClient } from '@tanstack/react-query'
import { useI18n } from '@/lib/i18n'
import { calculateInvoice, type VatRegime } from '@/lib/invoicing'
import { formatDate, INVOICE_STATUSES } from '@/lib/constants'
import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Skeleton } from '@/components/ui/skeleton'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Separator } from '@/components/ui/separator'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { AlertTriangle, Banknote, ChevronDown, ChevronUp, CircleDollarSign, Download, FileCheck2, Plus, Receipt, Search, Send, Trash2, TrendingUp, XCircle } from 'lucide-react'
import { PaginationFooter } from '@/components/shared/pagination-footer'
import { ListPageSkeleton } from '@/components/shared/list-page-skeleton'
import { PageHero } from '@/components/shared/page-hero'
import { useDebouncedValue } from '@/lib/hooks/use-debounced-value'
import type { PaginationMeta } from '@/lib/pagination'

type Party = { name: string; address: string | null; city: string; country: string; phone: string | null; email: string | null; taxId: string | null }
type InvoiceItem = { description: string; quantity: number; unit: string; unitPrice: number; discountRate: number; taxRate: number; taxAmount: number; total: number }
type InvoicePayment = { amount: number; method: string | null; reference: string | null; status: string; confirmedAt: string | null; createdAt: string }
type Invoice = {
  id: string; invoiceNumber: string; status: string; issuedAt: string | null; supplyDate: string | null; dueDate: string | null
  paidAmount: number; totalAmount: number; discountAmount: number; taxRate: number; taxAmount: number; netAmount: number
  vatRegime: VatRegime; vatLegalReference: string | null; vatWithholdingRate: number; vatWithholdingAmount: number
  withholdingTaxRate: number; withholdingTaxAmount: number; amountPayable: number; paymentTerms: string | null
  purchaseOrderRef: string | null; notes: string | null; currency: string; organization: Party; client: Party
  case: { reference: string } | null; payments: InvoicePayment[]; items: InvoiceItem[]
}
type InvoiceSummary = Omit<Invoice, 'organization' | 'client' | 'payments' | 'items'> & { organization: Pick<Party, 'name'>; client: Pick<Party, 'name'> }
type LineForm = { description: string; quantity: string; unit: string; unitPrice: string; discountRate: string; taxRate: string }
type InvoiceForm = {
  clientId: string; caseId: string; currency: string; issuedAt: string; supplyDate: string; dueDate: string
  vatRegime: VatRegime; vatLegalReference: string; vatWithholdingRate: string; withholdingTaxRate: string
  paymentTerms: string; purchaseOrderRef: string; notes: string; status: string; items: LineForm[]
}

const today = () => new Date().toISOString().slice(0, 10)
const dueIn = (days: number) => { const value = new Date(); value.setDate(value.getDate() + days); return value.toISOString().slice(0, 10) }
const emptyLine = (): LineForm => ({ description: '', quantity: '1', unit: 'prestation', unitPrice: '', discountRate: '0', taxRate: '18' })
const initialForm = (): InvoiceForm => ({ clientId: '', caseId: '', currency: 'GNF', issuedAt: today(), supplyDate: today(), dueDate: dueIn(30), vatRegime: 'standard', vatLegalReference: '', vatWithholdingRate: '0', withholdingTaxRate: '0', paymentTerms: 'Paiement à 30 jours par virement, chèque ou mobile money.', purchaseOrderRef: '', notes: '', status: 'brouillon', items: [emptyLine()] })
const money = (amount: number, currency = 'GNF') => new Intl.NumberFormat('fr-FR', { style: 'currency', currency, maximumFractionDigits: currency === 'GNF' ? 0 : 2 }).format(amount || 0)
const safeDate = (value: string | null) => value ? formatDate(value) : '—'

function statusLabel(status: string) { return INVOICE_STATUSES.find((item) => item.value === status)?.label ?? status }
function statusColor(status: string) {
  return ({ brouillon: 'bg-slate-100 text-slate-700', emise: 'bg-cyan-100 text-cyan-800', envoyee: 'bg-blue-100 text-blue-800', payee: 'bg-emerald-100 text-emerald-800', partiellement_payee: 'bg-amber-100 text-amber-800', echue: 'bg-red-100 text-red-800', annulee: 'bg-gray-200 text-gray-600' } as Record<string, string>)[status] || 'bg-slate-100 text-slate-700'
}
function payable(invoice: Pick<Invoice, 'amountPayable' | 'netAmount'>) { return invoice.amountPayable > 0 ? invoice.amountPayable : invoice.netAmount }

async function fetchInvoiceDetail(id: string) {
  const response = await fetch(`/api/invoices/${id}`)
  const payload = await response.json()
  if (!response.ok) throw new Error(payload.error || 'Facture indisponible')
  return payload as Invoice
}

async function downloadInvoice(summary: InvoiceSummary) {
  const invoice = await fetchInvoiceDetail(summary.id)
  const { default: JsPDF } = await import('jspdf')
  const doc = new JsPDF({ unit: 'mm', format: 'a4' })
  const width = 210
  doc.setFillColor(7, 62, 70); doc.rect(0, 0, width, 38, 'F')
  doc.setTextColor(255, 255, 255); doc.setFontSize(20); doc.setFont('helvetica', 'bold'); doc.text(invoice.organization.name, 16, 17)
  doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.text([invoice.organization.address || '', `${invoice.organization.city}, ${invoice.organization.country}`, invoice.organization.phone || '', invoice.organization.email || ''].filter(Boolean), 16, 23)
  doc.setFontSize(22); doc.setFont('helvetica', 'bold'); doc.text('FACTURE', 194, 17, { align: 'right' })
  doc.setFontSize(10); doc.text(invoice.invoiceNumber, 194, 25, { align: 'right' })
  doc.setTextColor(30, 41, 59); doc.setFontSize(9)
  doc.text(`NIF fournisseur : ${invoice.organization.taxId || 'Non renseigné'}`, 16, 45)
  doc.setFont('helvetica', 'bold'); doc.text('FACTURÉ À', 16, 57); doc.setFont('helvetica', 'normal')
  doc.text([invoice.client.name, invoice.client.address || '', `${invoice.client.city}, ${invoice.client.country}`, `NIF : ${invoice.client.taxId || 'Non renseigné'}`, invoice.client.phone || '', invoice.client.email || ''].filter(Boolean), 16, 63)
  doc.setFont('helvetica', 'bold'); doc.text('RÉFÉRENCES', 120, 57); doc.setFont('helvetica', 'normal')
  doc.text([`Émission : ${safeDate(invoice.issuedAt)}`, `Échéance : ${safeDate(invoice.dueDate)}`, `Dossier : ${invoice.case?.reference || 'Sans dossier'}`, `Bon de commande : ${invoice.purchaseOrderRef || '—'}`], 120, 63)
  let y = 93
  doc.setFillColor(226, 232, 240); doc.rect(16, y - 6, 178, 8, 'F'); doc.setFont('helvetica', 'bold')
  doc.text('Description', 18, y); doc.text('Qté', 115, y, { align: 'right' }); doc.text('P.U. HT', 151, y, { align: 'right' }); doc.text('Total HT', 192, y, { align: 'right' })
  doc.setFont('helvetica', 'normal'); y += 8
  invoice.items.forEach((item) => {
    if (y > 225) { doc.addPage(); y = 24 }
    const description = doc.splitTextToSize(item.description, 86)
    doc.text(description, 18, y); doc.text(`${item.quantity} ${item.unit}`, 115, y, { align: 'right' }); doc.text(money(item.unitPrice, invoice.currency), 151, y, { align: 'right' }); doc.text(money(item.total, invoice.currency), 192, y, { align: 'right' })
    y += Math.max(8, description.length * 5)
  })
  y = Math.max(y + 5, 150); doc.line(112, y, 194, y); y += 7
  const totalLine = (label: string, value: number, bold = false) => { doc.setFont('helvetica', bold ? 'bold' : 'normal'); doc.text(label, 118, y); doc.text(money(value, invoice.currency), 192, y, { align: 'right' }); y += 7 }
  totalLine('Total HT', invoice.totalAmount); totalLine(`TVA (${invoice.taxRate} %)`, invoice.taxAmount); totalLine('Total TTC', invoice.netAmount, true)
  if (invoice.vatWithholdingAmount > 0) totalLine(`Retenue TVA (${invoice.vatWithholdingRate} %)`, -invoice.vatWithholdingAmount)
  if (invoice.withholdingTaxAmount > 0) totalLine(`Retenue à la source (${invoice.withholdingTaxRate} %)`, -invoice.withholdingTaxAmount)
  doc.setFillColor(7, 62, 70); doc.rect(112, y - 5, 82, 11, 'F'); doc.setTextColor(255, 255, 255); doc.setFont('helvetica', 'bold'); doc.text('NET À PAYER', 118, y + 2); doc.text(money(payable(invoice), invoice.currency), 192, y + 2, { align: 'right' })
  doc.setTextColor(71, 85, 105); y += 18; doc.setFontSize(8); doc.setFont('helvetica', 'normal')
  if (invoice.vatLegalReference) doc.text(doc.splitTextToSize(`Mention fiscale : ${invoice.vatLegalReference}`, 178), 16, y)
  doc.text(doc.splitTextToSize(`Conditions : ${invoice.paymentTerms || 'Paiement selon conditions convenues.'}`, 178), 16, y + 9)
  if (invoice.notes) doc.text(doc.splitTextToSize(`Observations : ${invoice.notes}`, 178), 16, y + 18)
  doc.setTextColor(100, 116, 139); doc.text('Document généré par IGS Logistics Platform', 105, 287, { align: 'center' })
  doc.save(`${invoice.invoiceNumber}.pdf`)
}

function StatCard({ label, value, detail, icon, tone }: { label: string; value: string; detail: string; icon: React.ReactNode; tone: string }) {
  return <Card className="overflow-hidden border-0 shadow-sm"><div className={`h-1 ${tone}`} /><div className="flex items-center gap-4 p-5"><div className="rounded-2xl bg-slate-100 p-3 text-slate-700">{icon}</div><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-muted-foreground">{label}</p><p className="mt-1 text-xl font-bold">{value}</p><p className="text-xs text-muted-foreground">{detail}</p></div></div></Card>
}

function InvoiceDetail({ invoice, busy, onStatus, onPayment }: { invoice: Invoice; busy: boolean; onStatus: (invoice: Invoice, status: string) => void; onPayment: (invoice: Invoice) => void }) {
  const remaining = Math.max(0, payable(invoice) - invoice.paidAmount)
  return <TableRow><TableCell colSpan={9} className="bg-slate-50/80 p-0"><div className="grid gap-6 p-5 lg:grid-cols-[1.4fr_.8fr]">
    <div><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold">Détail de la facture</h3><div className="flex flex-wrap gap-2">
      <Button size="sm" variant="outline" onClick={() => { void downloadInvoice(invoice) }}><Download className="mr-2 h-4 w-4" />PDF</Button>
      {invoice.status === 'brouillon' && <Button size="sm" disabled={busy} onClick={() => onStatus(invoice, 'emise')}><FileCheck2 className="mr-2 h-4 w-4" />Émettre</Button>}
      {invoice.status === 'emise' && <Button size="sm" disabled={busy} onClick={() => onStatus(invoice, 'envoyee')}><Send className="mr-2 h-4 w-4" />Marquer envoyée</Button>}
      {!['brouillon', 'payee', 'annulee'].includes(invoice.status) && remaining > 0 && <Button size="sm" onClick={() => onPayment(invoice)}><Banknote className="mr-2 h-4 w-4" />Encaisser</Button>}
      {!['payee', 'annulee'].includes(invoice.status) && invoice.paidAmount === 0 && <Button size="sm" variant="ghost" className="text-destructive" disabled={busy} onClick={() => onStatus(invoice, 'annulee')}>Annuler</Button>}
    </div></div>
    <div className="overflow-hidden rounded-xl border bg-white"><Table><TableHeader><TableRow><TableHead>Prestation</TableHead><TableHead className="text-right">Qté</TableHead><TableHead className="text-right">Remise</TableHead><TableHead className="text-right">TVA</TableHead><TableHead className="text-right">Total HT</TableHead></TableRow></TableHeader><TableBody>{invoice.items.map((item, index) => <TableRow key={index}><TableCell><p className="font-medium">{item.description}</p><p className="text-xs text-muted-foreground">{money(item.unitPrice, invoice.currency)} / {item.unit}</p></TableCell><TableCell className="text-right">{item.quantity}</TableCell><TableCell className="text-right">{item.discountRate}%</TableCell><TableCell className="text-right">{item.taxRate}%</TableCell><TableCell className="text-right font-medium">{money(item.total, invoice.currency)}</TableCell></TableRow>)}</TableBody></Table></div>
    {invoice.vatLegalReference && <p className="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900"><strong>Mention fiscale :</strong> {invoice.vatLegalReference}</p>}</div>
    <div className="space-y-4"><div className="rounded-xl border bg-white p-4"><h4 className="mb-3 text-sm font-semibold">Synthèse</h4><div className="space-y-2 text-sm"><div className="flex justify-between"><span>HT</span><span>{money(invoice.totalAmount, invoice.currency)}</span></div><div className="flex justify-between"><span>TVA</span><span>{money(invoice.taxAmount, invoice.currency)}</span></div><div className="flex justify-between font-semibold"><span>TTC</span><span>{money(invoice.netAmount, invoice.currency)}</span></div>{invoice.vatWithholdingAmount > 0 && <div className="flex justify-between text-amber-700"><span>Retenue TVA</span><span>-{money(invoice.vatWithholdingAmount, invoice.currency)}</span></div>}{invoice.withholdingTaxAmount > 0 && <div className="flex justify-between text-amber-700"><span>Retenue source</span><span>-{money(invoice.withholdingTaxAmount, invoice.currency)}</span></div>}<Separator /><div className="flex justify-between text-base font-bold"><span>Net à payer</span><span>{money(payable(invoice), invoice.currency)}</span></div><div className="flex justify-between text-emerald-700"><span>Encaissé</span><span>{money(invoice.paidAmount, invoice.currency)}</span></div><div className="flex justify-between text-red-700"><span>Solde</span><span>{money(remaining, invoice.currency)}</span></div></div></div>
    <div className="rounded-xl border bg-white p-4"><h4 className="mb-3 text-sm font-semibold">Encaissements</h4>{invoice.payments.length ? <div className="space-y-2">{invoice.payments.map((payment, index) => <div key={index} className="flex justify-between text-sm"><div><p className="font-medium">{payment.method || 'Non précisé'}</p><p className="text-xs text-muted-foreground">{payment.reference || formatDate(payment.confirmedAt || payment.createdAt)}</p></div><span className="font-semibold">{money(payment.amount, invoice.currency)}</span></div>)}</div> : <p className="text-sm text-muted-foreground">Aucun paiement enregistré.</p>}</div></div>
  </div></TableCell></TableRow>
}

export default function InvoicesList() {
  const { t } = useI18n(); const queryClient = useQueryClient()
  const [statusFilter, setStatusFilter] = useState('all'); const [search, setSearch] = useState(''); const [expandedId, setExpandedId] = useState<string | null>(null)
  const [page, setPage] = useState(1); const debouncedSearch = useDebouncedValue(search)
  const [createOpen, setCreateOpen] = useState(false); const [form, setForm] = useState<InvoiceForm>(initialForm); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false)
  const [paymentInvoice, setPaymentInvoice] = useState<InvoiceSummary | null>(null); const [payment, setPayment] = useState({ amount: '', method: 'virement', reference: '', notes: '' })
  const { data, isLoading, isFetching, isError } = useQuery<{ items: InvoiceSummary[]; pagination: PaginationMeta; summary: { billed: number; collected: number; outstanding: number; overdue: number } }>({ queryKey: ['invoices', statusFilter, debouncedSearch, page], queryFn: async () => { const params = new URLSearchParams({ page: String(page), pageSize: '15' }); if (statusFilter !== 'all') params.set('status', statusFilter); if (debouncedSearch) params.set('search', debouncedSearch); const response = await fetch(`/api/invoices?${params}`); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); return payload }, placeholderData: keepPreviousData })
  const { data: expandedInvoice, isFetching: detailLoading } = useQuery<Invoice>({ queryKey: ['invoice-detail', expandedId], queryFn: () => fetchInvoiceDetail(expandedId!), enabled: Boolean(expandedId), staleTime: 30_000 })
  const { data: clients = [] } = useQuery<Array<{ id: string; name: string; taxId?: string }>>({ queryKey: ['invoice-clients'], queryFn: async () => { const response = await fetch('/api/clients'); if (!response.ok) throw new Error('Clients indisponibles'); return response.json() } })
  const { data: cases = [] } = useQuery<Array<{ id: string; reference: string; clientId: string }>>({ queryKey: ['invoice-cases'], queryFn: async () => { const response = await fetch('/api/cases?compact=true&pageSize=100'); if (!response.ok) throw new Error('Dossiers indisponibles'); const payload = await response.json(); return payload.items } })
  const invoices = data?.items ?? []
  const totals = useMemo(() => calculateInvoice(form.items.map((item) => ({ description: item.description, quantity: Number(item.quantity) || 0, unit: item.unit, unitPrice: Number(item.unitPrice) || 0, discountRate: Number(item.discountRate) || 0, taxRate: Number(item.taxRate) || 0 })), { vatRegime: form.vatRegime, vatWithholdingRate: Number(form.vatWithholdingRate), withholdingTaxRate: Number(form.withholdingTaxRate) }), [form.items, form.vatRegime, form.vatWithholdingRate, form.withholdingTaxRate])
  const filteredCases = cases.filter((item) => !form.clientId || item.clientId === form.clientId)
  const billed = data?.summary.billed ?? 0; const collected = data?.summary.collected ?? 0; const outstanding = data?.summary.outstanding ?? 0; const overdue = data?.summary.overdue ?? 0

  const updateLine = (index: number, key: keyof LineForm, value: string) => setForm((current) => ({ ...current, items: current.items.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item) }))
  async function createInvoice(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { const response = await fetch('/api/invoices', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, caseId: form.caseId || null, items: form.items.map((item) => ({ ...item, quantity: Number(item.quantity), unitPrice: Number(item.unitPrice), discountRate: Number(item.discountRate), taxRate: Number(item.taxRate) })) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Création impossible'); setCreateOpen(false); setForm(initialForm()); await queryClient.invalidateQueries({ queryKey: ['invoices'] }) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Erreur inconnue') } finally { setBusy(false) } }
  async function changeStatus(invoice: Invoice, status: string) { setBusy(true); setError(null); try { const response = await fetch(`/api/invoices/${invoice.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); await queryClient.invalidateQueries({ queryKey: ['invoices'] }); await queryClient.invalidateQueries({ queryKey: ['invoice-detail', invoice.id] }) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Mise à jour impossible') } finally { setBusy(false) } }
  function openPayment(invoice: InvoiceSummary | Invoice) { const balance = Math.max(0, payable(invoice) - invoice.paidAmount); setPayment({ amount: String(balance), method: 'virement', reference: '', notes: '' }); setPaymentInvoice(invoice); setError(null) }
  async function recordPayment(event: FormEvent) { event.preventDefault(); if (!paymentInvoice) return; setBusy(true); setError(null); try { const response = await fetch('/api/payments', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ invoiceId: paymentInvoice.id, amount: Number(payment.amount), method: payment.method, reference: payment.reference, notes: payment.notes, currency: paymentInvoice.currency }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setPaymentInvoice(null); await queryClient.invalidateQueries({ queryKey: ['invoices'] }) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Encaissement impossible') } finally { setBusy(false) } }

  if (isLoading) return <ListPageSkeleton cards={4} />
  if (isError) return <div className="flex min-h-80 flex-col items-center justify-center gap-3"><XCircle className="h-12 w-12 text-destructive" /><h2 className="text-xl font-semibold">Facturation indisponible</h2><p className="text-muted-foreground">Impossible de charger les factures.</p></div>
  return <div className="space-y-6">
    <PageHero eyebrow="Finance et recouvrement" title={t('screen.invoices')} description="Factures professionnelles, fiscalité guinéenne configurable et suivi des encaissements." actions={<Button onClick={() => { setForm(initialForm()); setError(null); setCreateOpen(true) }}><Plus className="mr-2 h-4 w-4" />Nouvelle facture</Button>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Chiffre facturé" value={money(billed)} detail="TTC hors annulations" icon={<TrendingUp />} tone="bg-cyan-600" /><StatCard label="Encaissé" value={money(collected)} detail={billed ? `${Math.round(collected / billed * 100)} % du facturé` : 'Aucun encaissement'} icon={<CircleDollarSign />} tone="bg-emerald-500" /><StatCard label="À recouvrer" value={money(outstanding)} detail="Net restant à payer" icon={<Banknote />} tone="bg-amber-500" /><StatCard label="Échéances dépassées" value={String(overdue)} detail="Factures avec solde" icon={<AlertTriangle />} tone="bg-red-500" /></div>
    {error && !createOpen && !paymentInvoice && <div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>}
    <Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b bg-slate-50/70 p-4 sm:flex-row sm:items-center"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="bg-white pl-9" placeholder="N° facture, client ou dossier..." value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); setExpandedId(null) }} /></div><Select value={statusFilter} onValueChange={(value) => { setStatusFilter(value); setPage(1); setExpandedId(null) }}><SelectTrigger className="w-full bg-white sm:w-52"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Tous les statuts</SelectItem>{INVOICE_STATUSES.map((item) => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select><span className="text-sm text-muted-foreground">{data?.pagination.total ?? 0} résultat{(data?.pagination.total ?? 0) > 1 ? 's' : ''}</span></div>
      <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead className="w-10" /><TableHead>Facture</TableHead><TableHead>Client / dossier</TableHead><TableHead className="text-right">TTC</TableHead><TableHead className="text-right">Net à payer</TableHead><TableHead className="text-right">Solde</TableHead><TableHead>Échéance</TableHead><TableHead>Statut</TableHead><TableHead className="w-12" /></TableRow></TableHeader><TableBody>{invoices.length ? invoices.map((invoice) => <Fragment key={invoice.id}><TableRow className="cursor-pointer" onClick={() => setExpandedId(expandedId === invoice.id ? null : invoice.id)}><TableCell>{expandedId === invoice.id ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}</TableCell><TableCell><p className="font-mono font-semibold">{invoice.invoiceNumber}</p><p className="text-xs text-muted-foreground">{safeDate(invoice.issuedAt)}</p></TableCell><TableCell><p className="font-medium">{invoice.client?.name || '—'}</p><p className="font-mono text-xs text-muted-foreground">{invoice.case?.reference || 'Sans dossier'}</p></TableCell><TableCell className="text-right font-medium">{money(invoice.netAmount, invoice.currency)}</TableCell><TableCell className="text-right">{money(payable(invoice), invoice.currency)}</TableCell><TableCell className="text-right font-semibold text-red-700">{money(Math.max(0, payable(invoice) - invoice.paidAmount), invoice.currency)}</TableCell><TableCell>{safeDate(invoice.dueDate)}</TableCell><TableCell><Badge className={statusColor(invoice.status)}>{statusLabel(invoice.status)}</Badge></TableCell><TableCell><Button variant="ghost" size="icon" onClick={(event) => { event.stopPropagation(); void downloadInvoice(invoice) }}><Download className="h-4 w-4" /></Button></TableCell></TableRow>{expandedId === invoice.id ? expandedInvoice ? <InvoiceDetail invoice={expandedInvoice} busy={busy} onStatus={changeStatus} onPayment={openPayment} /> : <TableRow><TableCell colSpan={9} className="p-6"><Skeleton className="h-40 w-full" aria-label={detailLoading ? 'Chargement de la facture' : 'Facture indisponible'} /></TableCell></TableRow> : null}</Fragment>) : <TableRow><TableCell colSpan={9} className="h-32 text-center text-muted-foreground">Aucune facture ne correspond aux filtres.</TableCell></TableRow>}</TableBody></Table></div>
      {data?.pagination ? <PaginationFooter pagination={data.pagination} onPageChange={(next) => { setPage(next); setExpandedId(null) }} loading={isFetching} /> : null}
    </Card>

    <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent className="max-h-[94vh] max-w-6xl overflow-y-auto"><DialogHeader><DialogTitle className="text-xl">Établir une facture</DialogTitle></DialogHeader><form onSubmit={createInvoice} className="space-y-6"><div className="grid gap-6 lg:grid-cols-[1fr_330px]"><div className="space-y-6"><section className="grid gap-4 rounded-xl border p-4 md:grid-cols-3"><div className="grid gap-2 md:col-span-2"><Label>Client *</Label><Select value={form.clientId} onValueChange={(value) => setForm((current) => ({ ...current, clientId: value, caseId: '' }))}><SelectTrigger><SelectValue placeholder="Sélectionner le client" /></SelectTrigger><SelectContent>{clients.map((client) => <SelectItem key={client.id} value={client.id}>{client.name}{client.taxId ? ` · NIF ${client.taxId}` : ''}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label>Dossier</Label><Select value={form.caseId || 'none'} onValueChange={(value) => setForm((current) => ({ ...current, caseId: value === 'none' ? '' : value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Sans dossier</SelectItem>{filteredCases.map((item) => <SelectItem key={item.id} value={item.id}>{item.reference}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label>Date d’émission</Label><Input type="date" value={form.issuedAt} onChange={(event) => setForm((current) => ({ ...current, issuedAt: event.target.value }))} /></div><div className="grid gap-2"><Label>Date de prestation</Label><Input type="date" value={form.supplyDate} onChange={(event) => setForm((current) => ({ ...current, supplyDate: event.target.value }))} /></div><div className="grid gap-2"><Label>Échéance</Label><Input type="date" value={form.dueDate} onChange={(event) => setForm((current) => ({ ...current, dueDate: event.target.value }))} /></div><div className="grid gap-2"><Label>Bon de commande / référence</Label><Input value={form.purchaseOrderRef} onChange={(event) => setForm((current) => ({ ...current, purchaseOrderRef: event.target.value }))} placeholder="BC-2026-..." /></div><div className="grid gap-2"><Label>Devise</Label><Select value={form.currency} onValueChange={(value) => setForm((current) => ({ ...current, currency: value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="GNF">GNF · Franc guinéen</SelectItem><SelectItem value="USD">USD · Dollar</SelectItem><SelectItem value="EUR">EUR · Euro</SelectItem></SelectContent></Select></div><div className="grid gap-2"><Label>Création</Label><Select value={form.status} onValueChange={(value) => setForm((current) => ({ ...current, status: value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="brouillon">En brouillon</SelectItem><SelectItem value="emise">Émettre maintenant</SelectItem></SelectContent></Select></div></section>
      <section><div className="mb-3 flex items-center justify-between"><div><h3 className="font-semibold">Prestations facturées</h3><p className="text-xs text-muted-foreground">Quantités, unités, remises et TVA par ligne.</p></div><Button type="button" variant="outline" size="sm" onClick={() => setForm((current) => ({ ...current, items: [...current.items, emptyLine()] }))}><Plus className="mr-2 h-4 w-4" />Ajouter une ligne</Button></div><div className="space-y-3">{form.items.map((item, index) => <div key={index} className="grid gap-3 rounded-xl border bg-slate-50/60 p-3 md:grid-cols-[minmax(180px,2fr)_80px_110px_130px_90px_80px_40px]"><div className="grid gap-1"><Label className="text-xs">Description *</Label><Input value={item.description} onChange={(event) => updateLine(index, 'description', event.target.value)} placeholder="Transit, manutention, transport..." /></div><div className="grid gap-1"><Label className="text-xs">Qté</Label><Input type="number" min="0.01" step="0.01" value={item.quantity} onChange={(event) => updateLine(index, 'quantity', event.target.value)} /></div><div className="grid gap-1"><Label className="text-xs">Unité</Label><Input value={item.unit} onChange={(event) => updateLine(index, 'unit', event.target.value)} /></div><div className="grid gap-1"><Label className="text-xs">Prix unitaire HT</Label><Input type="number" min="0" step="0.01" value={item.unitPrice} onChange={(event) => updateLine(index, 'unitPrice', event.target.value)} /></div><div className="grid gap-1"><Label className="text-xs">Remise %</Label><Input type="number" min="0" max="100" value={item.discountRate} onChange={(event) => updateLine(index, 'discountRate', event.target.value)} /></div><div className="grid gap-1"><Label className="text-xs">TVA %</Label><Input type="number" min="0" disabled={form.vatRegime !== 'standard'} value={form.vatRegime === 'standard' ? item.taxRate : '0'} onChange={(event) => updateLine(index, 'taxRate', event.target.value)} /></div><div className="flex items-end"><Button type="button" variant="ghost" size="icon" disabled={form.items.length === 1} onClick={() => setForm((current) => ({ ...current, items: current.items.filter((_, itemIndex) => itemIndex !== index) }))}><Trash2 className="h-4 w-4 text-destructive" /></Button></div></div>)}</div></section>
      <section className="grid gap-4 rounded-xl border p-4 md:grid-cols-2"><div className="grid gap-2"><Label>Conditions de paiement</Label><Textarea value={form.paymentTerms} onChange={(event) => setForm((current) => ({ ...current, paymentTerms: event.target.value }))} /></div><div className="grid gap-2"><Label>Observations</Label><Textarea value={form.notes} onChange={(event) => setForm((current) => ({ ...current, notes: event.target.value }))} placeholder="Coordonnées bancaires, instructions ou notes internes..." /></div></section></div>
      <aside className="space-y-4"><div className="rounded-xl border bg-slate-50 p-4"><h3 className="mb-4 font-semibold">Traitement fiscal</h3><div className="space-y-4"><div className="grid gap-2"><Label>Régime TVA</Label><Select value={form.vatRegime} onValueChange={(value: VatRegime) => setForm((current) => ({ ...current, vatRegime: value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="standard">TVA standard (18 %)</SelectItem><SelectItem value="zero_export">Taux 0 % · export / international</SelectItem><SelectItem value="exonere">Opération exonérée</SelectItem></SelectContent></Select></div>{form.vatRegime !== 'standard' && <div className="grid gap-2"><Label>Référence légale / motif *</Label><Textarea value={form.vatLegalReference} onChange={(event) => setForm((current) => ({ ...current, vatLegalReference: event.target.value }))} placeholder="Article du CGI et nature de l’opération" /></div>}<div className="grid gap-2"><Label>Retenue de TVA par le client</Label><Select value={form.vatWithholdingRate} onValueChange={(value) => setForm((current) => ({ ...current, vatWithholdingRate: value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="0">Aucune</SelectItem><SelectItem value="50">50 % de la TVA</SelectItem></SelectContent></Select><p className="text-[11px] text-muted-foreground">À activer notamment pour certains clients publics, miniers, pétroliers ou télécoms concernés.</p></div><div className="grid gap-2"><Label>Retenue à la source</Label><Select value={form.withholdingTaxRate} onValueChange={(value) => setForm((current) => ({ ...current, withholdingTaxRate: value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="0">Aucune</SelectItem><SelectItem value="10">10 % · prestations concernées</SelectItem><SelectItem value="15">15 % · non-résident</SelectItem></SelectContent></Select></div></div></div>
      <div className="sticky top-0 rounded-xl bg-[#073e46] p-5 text-white shadow-lg"><p className="text-xs font-semibold uppercase tracking-widest text-cyan-200">Récapitulatif</p><div className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><span>Montant HT</span><span>{money(totals.totalAmount, form.currency)}</span></div>{totals.discountAmount > 0 && <div className="flex justify-between text-amber-200"><span>Remises incluses</span><span>{money(totals.discountAmount, form.currency)}</span></div>}<div className="flex justify-between"><span>TVA</span><span>{money(totals.taxAmount, form.currency)}</span></div><div className="flex justify-between font-semibold"><span>Total TTC</span><span>{money(totals.netAmount, form.currency)}</span></div>{totals.vatWithholdingAmount > 0 && <div className="flex justify-between text-amber-200"><span>Retenue TVA</span><span>-{money(totals.vatWithholdingAmount, form.currency)}</span></div>}{totals.withholdingTaxAmount > 0 && <div className="flex justify-between text-amber-200"><span>Retenue source</span><span>-{money(totals.withholdingTaxAmount, form.currency)}</span></div>}<div className="my-3 border-t border-white/20" /><div className="flex justify-between text-lg font-bold"><span>Net à payer</span><span>{money(totals.amountPayable, form.currency)}</span></div></div></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-relaxed text-amber-950"><strong>Contrôle fiscal.</strong> Les exonérations et retenues dépendent du client et de l’opération. Faites valider le traitement par votre comptable ou la DGI avant émission définitive.</div></aside></div>{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}<DialogFooter><Button type="button" variant="outline" onClick={() => setCreateOpen(false)}>Annuler</Button><Button disabled={busy || !form.clientId || totals.totalAmount <= 0} type="submit">{busy ? 'Enregistrement...' : form.status === 'emise' ? 'Créer et émettre' : 'Enregistrer le brouillon'}</Button></DialogFooter></form></DialogContent></Dialog>

    <Dialog open={Boolean(paymentInvoice)} onOpenChange={(open) => !open && setPaymentInvoice(null)}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>Enregistrer un encaissement</DialogTitle></DialogHeader><form onSubmit={recordPayment} className="space-y-4"><div className="rounded-xl bg-slate-50 p-4"><p className="text-sm text-muted-foreground">{paymentInvoice?.invoiceNumber}</p><p className="text-lg font-bold">Solde : {paymentInvoice ? money(Math.max(0, payable(paymentInvoice) - paymentInvoice.paidAmount), paymentInvoice.currency) : ''}</p></div><div className="grid gap-2"><Label>Montant encaissé *</Label><Input type="number" min="0.01" step="0.01" value={payment.amount} onChange={(event) => setPayment((current) => ({ ...current, amount: event.target.value }))} /></div><div className="grid gap-2"><Label>Mode de paiement</Label><Select value={payment.method} onValueChange={(value) => setPayment((current) => ({ ...current, method: value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="virement">Virement bancaire</SelectItem><SelectItem value="cheque">Chèque</SelectItem><SelectItem value="especes">Espèces</SelectItem><SelectItem value="mobile_money">Mobile money</SelectItem></SelectContent></Select></div><div className="grid gap-2"><Label>Référence / reçu</Label><Input value={payment.reference} onChange={(event) => setPayment((current) => ({ ...current, reference: event.target.value }))} placeholder="N° transaction, chèque ou reçu" /></div><div className="grid gap-2"><Label>Observations</Label><Textarea value={payment.notes} onChange={(event) => setPayment((current) => ({ ...current, notes: event.target.value }))} /></div>{error && <p className="text-sm text-destructive">{error}</p>}<DialogFooter><Button type="button" variant="outline" onClick={() => setPaymentInvoice(null)}>Annuler</Button><Button disabled={busy} type="submit">{busy ? 'Validation...' : 'Confirmer l’encaissement'}</Button></DialogFooter></form></DialogContent></Dialog>
  </div>
}
