'use client'
import { useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Banknote, Plus } from 'lucide-react'
import { formatGNF, formatDate } from '@/lib/constants'
import { PageHero } from '@/components/shared/page-hero'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'

type Payment = { id: string; amount: number; method: string | null; operator: string | null; reference: string | null; mobileNumber: string | null; paidAt: string | null; createdAt: string; status: string }
export default function PaymentsView() {
  const client = useQueryClient(); const [open, setOpen] = useState(false); const [error, setError] = useState(''); const [form, setForm] = useState({ invoiceId: '', amount: '', method: 'virement', reference: '', mobileNumber: '', operator: '', paidAt: new Date().toISOString().slice(0, 10), receiptUrl: '' })
  const { data: payments = [] } = useQuery<Payment[]>({ queryKey: ['payments'], queryFn: async () => { const response = await fetch('/api/payments'); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); return payload } })
  const { data: invoices = [] } = useQuery<Array<{ id: string; invoiceNumber: string; amountPayable: number; paidAmount: number }>>({ queryKey: ['payment-invoices'], queryFn: async () => { const response = await fetch('/api/invoices?pageSize=100'); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); return payload.items } })
  const submit = async () => { setError(''); const response = await fetch('/api/payments', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, amount: Number(form.amount), provider: form.method === 'orange_money' ? 'orange_money' : form.method === 'mtn_money' ? 'mtn_money' : form.method === 'chap_chap' ? 'chap_chap' : 'manuel' }) }); const payload = await response.json(); if (!response.ok) return setError(payload.error); setOpen(false); await client.invalidateQueries({ queryKey: ['payments'] }) }
  return <div className="space-y-6"><PageHero eyebrow="TRÉSORERIE GUINÉE" title="Encaissements" description="Virement bancaire, espèces et mobile money avec références vérifiables." actions={<Button onClick={() => setOpen(true)}><Plus className="mr-2 h-4 w-4" />Saisir un encaissement</Button>} /><Card className="overflow-hidden"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Mode</TableHead><TableHead>Référence</TableHead><TableHead>Téléphone</TableHead><TableHead>Statut</TableHead><TableHead className="text-right">Montant</TableHead></TableRow></TableHeader><TableBody>{payments.length ? payments.map((payment) => <TableRow key={payment.id}><TableCell>{formatDate(payment.paidAt || payment.createdAt)}</TableCell><TableCell>{payment.operator || payment.method || 'Non précisé'}</TableCell><TableCell>{payment.reference || '—'}</TableCell><TableCell>{payment.mobileNumber || '—'}</TableCell><TableCell>{payment.status === 'confirme' ? 'Confirmé' : 'En attente'}</TableCell><TableCell className="text-right font-semibold">{formatGNF(payment.amount)}</TableCell></TableRow>) : <TableRow><TableCell colSpan={6}><div className="p-8 text-center text-muted-foreground"><Banknote className="mx-auto mb-2" />Aucun encaissement enregistré.</div></TableCell></TableRow>}</TableBody></Table></div></Card>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Nouvel encaissement</DialogTitle></DialogHeader><div className="grid gap-4"><div><Label>Facture *</Label><Select value={form.invoiceId} onValueChange={(value) => setForm({ ...form, invoiceId: value })}><SelectTrigger><SelectValue placeholder="Choisir la facture" /></SelectTrigger><SelectContent>{invoices.filter((invoice) => invoice.paidAmount < invoice.amountPayable).map((invoice) => <SelectItem key={invoice.id} value={invoice.id}>{invoice.invoiceNumber}</SelectItem>)}</SelectContent></Select></div><div><Label>Montant GNF *</Label><Input inputMode="numeric" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} /></div><div><Label>Mode *</Label><Select value={form.method} onValueChange={(value) => setForm({ ...form, method: value, operator: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="virement">Virement BCRG / banque locale</SelectItem><SelectItem value="especes">Espèces</SelectItem><SelectItem value="orange_money">Orange Money</SelectItem><SelectItem value="mtn_money">MTN Mobile Money</SelectItem><SelectItem value="chap_chap">Chap Chap Pay</SelectItem></SelectContent></Select></div>{['orange_money', 'mtn_money', 'chap_chap'].includes(form.method) && <><div><Label>Numéro +224 *</Label><Input placeholder="+224 622 00 00 00" value={form.mobileNumber} onChange={(event) => setForm({ ...form, mobileNumber: event.target.value })} /></div><div><Label>Justificatif (URL) *</Label><Input placeholder="https://…" value={form.receiptUrl} onChange={(event) => setForm({ ...form, receiptUrl: event.target.value })} /></div></>}<div><Label>Référence *</Label><Input placeholder="OM-2026-08-14-8891" value={form.reference} onChange={(event) => setForm({ ...form, reference: event.target.value })} /></div><div><Label>Date *</Label><Input type="date" value={form.paidAt} onChange={(event) => setForm({ ...form, paidAt: event.target.value })} /></div>{error && <p className="text-sm text-destructive">{error}</p>}</div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Annuler</Button><Button onClick={() => void submit()}>Enregistrer</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
