import { LegalPage, LegalSection } from '@/components/legal/legal-page'
import { legalIdentity } from '@/lib/legal'

export const metadata = { title: 'Politique de confidentialité | IGS Nexus' }

export default function PrivacyPage() {
  return <LegalPage title="Politique de confidentialité" description="Comment IGS Nexus collecte, utilise, protège et conserve les données personnelles des utilisateurs et contacts métier.">
    <LegalSection title="1. Responsable du traitement"><p>{legalIdentity.publisherName}, établi à {legalIdentity.address}, traite les données nécessaires à l’exploitation d’IGS Nexus. Les demandes relatives aux données peuvent être adressées à <a className="text-[#14554d] underline" href={`mailto:${legalIdentity.privacyEmail}`}>{legalIdentity.privacyEmail}</a>.</p></LegalSection>
    <LegalSection title="2. Données traitées"><p>Nous pouvons traiter les données d’identité et de contact, comptes et rôles, journaux de connexion et d’audit, informations sur les clients, dossiers logistiques, marchandises, documents, factures, paiements, incidents, positions et données de suivi fournies par l’utilisateur ou les intégrations activées.</p></LegalSection>
    <LegalSection title="3. Finalités et fondements"><p>Les traitements servent à exécuter le contrat SaaS, gérer les accès, assurer la sécurité et la traçabilité, fournir le suivi logistique, produire les documents et factures, traiter les paiements, répondre au support et respecter les obligations légales. Les communications commerciales non nécessaires reposent sur un consentement préalable lorsqu’il est requis.</p></LegalSection>
    <LegalSection title="4. Destinataires et sous-traitants"><p>Les données sont accessibles aux utilisateurs autorisés de l’organisation concernée et, selon les fonctions activées, à des prestataires techniques tels que Supabase (base, authentification et stockage), Vercel (hébergement), Stripe ou un prestataire de paiement, ShipsGo et AISStream pour le suivi maritime. Chaque transmission est limitée aux données nécessaires au service demandé.</p></LegalSection>
    <LegalSection title="5. Transferts internationaux"><p>Certains prestataires peuvent traiter des données hors de Guinée. L’éditeur sélectionne des prestataires offrant des garanties contractuelles et techniques appropriées et limite les données transférées. L’organisation cliente doit vérifier que ses propres usages et instructions sont compatibles avec ses obligations sectorielles.</p></LegalSection>
    <LegalSection title="6. Durées de conservation"><p>Les données de compte sont conservées pendant la relation contractuelle puis le temps nécessaire au règlement des obligations et litiges. Les pièces comptables et factures suivent la durée légale applicable. Les journaux de sécurité sont conservés pour une durée proportionnée aux besoins d’audit. Les sauvegardes sont supprimées selon leur cycle technique.</p></LegalSection>
    <LegalSection title="7. Sécurité"><p>IGS Nexus applique notamment l’isolation par organisation, des contrôles de rôles, la 2FA obligatoire pour les administrateurs, le verrouillage après échecs, la journalisation des actions sensibles, le chiffrement en transit et des liens temporaires pour les documents privés.</p></LegalSection>
    <LegalSection title="8. Vos droits"><p>Sous réserve de la loi applicable, vous pouvez demander l’information, l’accès, la rectification, l’opposition, la limitation ou la suppression de vos données. Une preuve d’identité peut être demandée. La demande est adressée à l’email indiqué ci-dessus; une réponse motivée sera fournie dans les délais applicables.</p></LegalSection>
    <LegalSection title="9. Cadre juridique"><p>Cette politique tient compte de la loi guinéenne L/2016/037/AN relative à la cybersécurité et à la protection des données à caractère personnel, ainsi que des textes applicables aux transactions électroniques.</p></LegalSection>
    <LegalSection title="10. Évolution"><p>La politique peut évoluer pour refléter les changements réglementaires et fonctionnels. La date de version est affichée en tête de page; une information renforcée sera fournie en cas de modification substantielle.</p></LegalSection>
  </LegalPage>
}
